version: "3.9"

services:
  database:
    image: postgres:14-alpine
    container_name: shopping-list-postgresql-database
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - shopping-list-data:/var/lib/postgresql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "${POSTGRES_PORT}:5432"
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost:${POSTGRES_PORT}"]
      interval: 10s
      timeout: 1s
      retries: 3

  backend-app:
    container_name: shopping_app_backend
    build:  "../shopping-list-backend/"
    env_file: ./.env
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USER
      - SPRING_DATASOURCE_PASSWORD

  frontend-app:
    container_name: shopping_app_frontend
    build: "../shopping-list-frontend/"
    env_file: ./.env
    ports:
      - "${FRONTEND_PORT}:80"

volumes:
  shopping-list-data:
