version: "3.9"

services:
  database:
    image: postgres:14-alpine
    container_name: shopping-list-postgresql-database
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - shopping-list-data:/var/lib/postgresql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - app-db
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost:5433"]
      interval: 10s
      timeout: 1s
      retries: 3
    profiles:
      - frontend
      - backend

volumes:
  shopping-list-data:

networks:
  app-db: